version: "3"

services:
  traefik:
    image: traefik:v1.7-alpine
    command:
      - --api
      - --docker
      - --docker.watch
      - --docker.constraints=tag==web
      - --metrics
      - --metrics.prometheus

      # NOTE: Toggle the lines below to enable SSL
      - --entryPoints=Name:http Address::80 Compress::true
      - --defaultEntryPoints=http
      # - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https Compress::true
      # - --entryPoints=Name:https Address::443 TLS:/ssl/ssl.crt,/ssl/ssl.key Compress::true
      # - --defaultentrypoints=http,https

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/null:/traefik.toml:rw
      # NOTE: Provide the SSL certs in the ./config folder below
      # - ./config:/ssl
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - codecov
    depends_on:
      - web
  web:
    image: codecov/enterprise-web:latest-stable #note: this is for setup purposes only, be sure to pin to the latest release from our changelog: https://docs.codecov.io/changelog
    command: web
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
    ports:
      - "5000"
    labels:
      - "traefik.tags=web"
      - "traefik.backend=web"
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /"
    environment:
      - STATSD_HOST=statsd
      - DATADOG_TRACE_ENABLED=false
    networks:
      - codecov
    depends_on:
      - statsd

  worker:
    image: codecov/enterprise-worker:latest-stable #note: this is for setup purposes only, be sure to pin to the latest release from our changelog: https://docs.codecov.io/changelog
    command: worker
    volumes:
      - ./codecov.yml:/config/codecov.yml:ro
    environment:
      - STATSD_HOST=statsd
      - DATADOG_TRACE_ENABLED=false
    networks:
      - codecov
    depends_on:
      - statsd
  
  statsd:
    image: prom/statsd-exporter:v0.6.0
    command: -statsd.listen-udp=:8125 -statsd.listen-tcp=:8125
    ports:
      - "8125"
      - "9102"
    networks:
      - codecov

networks:
  codecov:
    driver: bridge